---
title: "Detailed Example of hmList Usage"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Detailed Example of hmList Usage}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Detailed Example of `hmList`

This vignette provides a detailed example of how to use the `hmList` function to create a heatmap list from a list of matrices generated via the `matList` function. There are a range of customisation options available to alter the output. The function leverages the `EnrichedHeatmap`, `circlize`, `RColorBrewer`, `grdevices`, `stats`, `purrr`, and `graphics` packages to handle the data from the matrices and convert it into an attractive heatmap

## Prerequisites

Before we begin, ensure that you have the necessary packages installed and loaded:

```{r install_packages, eval=FALSE}
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install(version = "3.21")

if (!requireNamespace("purrr", quietly = TRUE)) {
  install.packages("purrr")
}
if (!requireNamespace("circlize", quietly = TRUE)) {
  install.packages("circlize")
}
if (!requireNamespace("RColorBrewer", quietly = TRUE)) {
  install.packages("RColorBrewer")
}
if (!requireNamespace("grDevices", quietly = TRUE)) {
  install.packages("grDevices")
}
if (!requireNamespace("stats", quietly = TRUE)) {
  install.packages("stats")
}
if (!requireNamespace("graphics", quietly = TRUE)) {
  install.packages("graphics")
}
if (!requireNamespace("EnrichedHeatmap", quietly = TRUE)) {
  BiocManager::install("EnrichedHeatmap")
}

# Once installed then load the required libraries

library(purrr)
library(circlize)
library(RColorBrewer)
library(grDevices)
library(stats)
library(graphics)
library(EnrichedHeatmap)
```

## Usage

In this case we are going to take a list of matrices called "matrixlist" generated from the `matList` function and use them to generate heatmaps using the `hmList` function

1. Selecting window sizes for plotting. In this case we will give 50 windows to the upstream flank, 100 to the full gene, and 50 to the downstream flank 

```r
# Specify the window sizes
windows <- c("Upstream" = 50, "Gene" = 100, "Downstream" = 50)
```

2. Creating our heatmaps with the following customisation options: (1) Blue to red colour scale (2) Labels "-50b", "TSS", "TES, "+50b" (3) Not to show row names

```r
# Generating our heatmap list
heatmaps <- hmList(
  matl = matrixlist, 
  wins = windows, 
  col_fun = "bl2rd", 
  show_row_names = FALSE, 
  win_labels = c("-50b", "TSS", "TES", "+50b")
  )
```
